# Generated by Django 4.2 on 2024-02-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='верификация'),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='PRLE6rA', max_length=10, verbose_name='Код вeрификации'),
        ),
    ]
