# Generated by Django 4.2 on 2024-03-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='_-vcRgE', max_length=10, verbose_name='Код вeрификации'),
        ),
    ]
