# Generated by Django 4.2 on 2024-02-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Просмотры'),
        ),
    ]
