# Generated by Django 4.2 on 2024-02-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250, verbose_name='продукт')),
                ('number_version', models.IntegerField(verbose_name='номер версии')),
                ('name_version', models.CharField(max_length=100, verbose_name='название версии')),
                ('is_active_version', models.BooleanField(default=True, verbose_name='признак версии')),
            ],
        ),
    ]
